global:
  resolve_timeout: 1m

route:
  receiver: stockflow-webhook
  group_by:
    - alertname
    - service
  group_wait: 1s
  group_interval: 5s
  repeat_interval: 4h

receivers:
  - name: stockflow-webhook
    webhook_configs:
      - url: http://alert-webhook:8080/alerts
        send_resolved: true
